version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello
      MYSQL_DATABASE: db_tasks_approach
      MYSQL_USER: nbjm
      MYSQL_PASSWORD: SU12mo34
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
